Feature/bot
cherryontech/comet-cruisers-spring2024 pull request #19
Opened 2024-05-26 21:03 UTC by yawnka

Jira Story Card / Issue Link
Spring 3 Mascot Bot Functionality

Description of PR:
Added the mascot bot with CSS that displays different dad jokes/affirmations/etc.
bot text from: https://docs.google.com/spreadsheets/d/16BrPG5-ioTw4L0QnN5dvOdazU_D5sSp5hhp-A4glgPQ/edit#gid=4148052

Type of change in this PR:
added a js page for functionality
added code of the fx ^ into home
added CSS code in tailwind css
Testing instructions:
npm start and click the starfish to get randomized output.

What I learned/had trouble with:
Functions, getting the srv image to display, CSS positioning.

2024-05-27 17:25 UTC, PaulaTam requested changes
- The Home.js needs to be re-edited to have the deleted stuff re-added as that is the current dashboard grid css.
- Some of the css in tailwind.css is the old css. I'll mark the parts I know with a comment.

2024-05-27 17:28 UTC, PaulaTam commented on src/pages/Home.js
> -      <div className="dashboard-grid">
- The deleted parts should be brought back as this is the current css.

2024-05-27 17:28 UTC, PaulaTam commented on src/pages/Home.js
> +      <h1 className="text-3xl font-bold underline">Title</h1>
- This part is old code, please remove.

2024-05-27 17:29 UTC, PaulaTam commented on src/pages/Home.js
> +      {displayMascot()}
The displayMascot() is fine where it is.

2024-05-27 17:34 UTC, PaulaTam commented on src/styles/tailwind.css
> -  .task-wrapper{
This task-wrapper (with the @apply) is the correct css.

2024-05-27 17:38 UTC, PaulaTam commented on src/styles/tailwind.css
> -.Collapsible__trigger{
This collapsible-trigger needs to be brought back. 

Just add a closing bracket at the end
`.Collapsible__trigger{
  color: #0E8992
}`

2024-06-02 22:06 UTC, closed without merging

2024-06-02 22:06 UTC, yawnka commented
old PR doesnt comply with updated branch, code used in feature/botFix